---
version: "3"

tasks:
  export-btt-config:
    desc: Export the BetterTouchTool configuration from BTT and save it to
      $PWD/home-manager/betterTouchTool/Default.bttpreset
    platforms: [darwin]
    cmd:
      osascript -e 'tell application "BetterTouchTool" to export_preset
      "BTT 3 Config" outputPath
      "{{.TASKFILE_DIR}}/home-manager/betterTouchTool/Default.bttpreset" with
      includeSettings'

  switch:
    desc: Build & switch nix configuration
    dir: .
    cmds:
      - platforms: ['linux']
        cmd: home-manager switch --flake .
      - platforms: ['darwin']
        cmd: darwin-rebuild switch --flake .
