SSOConfig:
    DefaultSSO:
        SSORegion: eu-west-1
        StartUrl: https://axis-communications.awsapps.com/start
        DefaultRegion: eu-west-1
DefaultSSO: DefaultSSO
DefaultRegion: eu-west-1
ConsoleDuration: 480 # 8 hours
CacheRefresh: 168
Threads: 5
AutoConfigCheck: true
LogLevel: warn
HistoryLimit: 10
HistoryMinutes: 1440
ProfileFormat: "{{ .AccountAlias }}:{{ .RoleName }}"
AccountPrimaryTag:
    - AccountName
    - AccountAlias
    - Email
PromptColors:
    SuggestionTextColor: Black
    SuggestionBGColor: Cyan
    DescriptionTextColor: Black
    DescriptionBGColor: LightGrey
    SelectedSuggestionTextColor: Black
    SelectedSuggestionBGColor: Fuchsia
    SelectedDescriptionBGColor: LightGrey
ListFields:
    - AccountId
    - AccountAlias
    - RoleName
    - Profile
    - ExpiresStr
