name: Neovim plugin diff commenter
on:
  pull_request:
    types: [opened,edited,reopened]
    paths:
      - '**/init.lua'
jobs:
  pr_body:
    if:  startsWith(github.head_ref, 'renovate/')
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Print body
        env:
          PR: ${{ toJson(github.event.pull_request) }}
          GH_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DIFF_OUTPUT=$(echo "$PR" | hack/diff.sh)
          # the eof is needed since output is multiline
          echo 'DIFF_OUTPUT<<EOF' >> $GITHUB_ENV
          echo "$DIFF_OUTPUT" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Print comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ${{ env.DIFF_OUTPUT }}

